window.onload = function() {
  var Drinks = document.getElementById('Drinks')
  Drinks.style.marginLeft = "25px";
  var Fruit = document.getElementById('Fruit')
  Fruit.style.marginLeft = "25px";
  var Apple = document.getElementById('Apple')
  Apple.style.marginLeft = "25px";
  var Grape = document.getElementById('Grape')
  Grape.style.marginLeft = "25px";
  var GApple = document.getElementById('GApple')
  GApple.style.marginLeft = "25px";
  var RApple = document.getElementById('RApple')
  RApple.style.marginLeft = "25px";
  var GGrape = document.getElementById('GGrape')
  GGrape.style.marginLeft = "25px";
  var PGrape = document.getElementById('PGrape')
  PGrape.style.marginLeft = "25px";
  var Soda = document.getElementById('Soda')
  Soda.style.marginLeft = "25px";
  var Juice = document.getElementById('Juice')
  Juice.style.marginLeft = "25px";
  var Coke = document.getElementById('Coke')
  Coke.style.marginLeft = "25px";
  var Sprite = document.getElementById('Sprite')
  Sprite.style.marginLeft = "25px";
  var Watermelon = document.getElementById('Watermelon')
  Watermelon.style.marginLeft = "25px";
  var Lemon = document.getElementById('Lemon')
  Lemon.style.marginLeft = "25px";
}
